/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalsoop;

import java.sql.Connection;
import java.sql.ResultSet;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author tulan
 */

public class schoolManagementMainUI extends javax.swing.JFrame {

    private String currentData = "";
    private Boolean boolAdd = true;
    private Connection conn = finalsConnect.Connect();
    private dbManager db = new dbManager(conn);
    private javax.swing.JTable populatedTable = null;
    private java.sql.ResultSet currentRs = null;

    /**
     * Creates new form schoolManagementMainUI
     */
    public schoolManagementMainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnManagement = new javax.swing.JButton();
        panelNav = new javax.swing.JPanel();
        btnSubjSched = new javax.swing.JButton();
        btnStudentGrades = new javax.swing.JButton();
        btnSchoolYear = new javax.swing.JButton();
        btnCollege = new javax.swing.JButton();
        btnSemester = new javax.swing.JButton();
        btnCourse = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        btnSubject = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        pnlDashboard = new javax.swing.JPanel();
        scrlDashboard = new javax.swing.JScrollPane();
        tblDashboard = new javax.swing.JTable();
        pnlManagement = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblManagement = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        pnlAddSubjSched = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBlockNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSequence = new javax.swing.JTextField();
        txtType = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRoom = new javax.swing.JTextField();
        txtTime = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbSubjectCode = new javax.swing.JComboBox<>();
        cmbDay = new javax.swing.JComboBox<>();
        cmbEmployeeName = new javax.swing.JComboBox<>();
        cmbSYear = new javax.swing.JComboBox<>();
        cmbSemester = new javax.swing.JComboBox<>();
        cmbCollegeCode = new javax.swing.JComboBox<>();
        btnConfirmSched = new javax.swing.JButton();
        btnAddCancel = new javax.swing.JButton();
        pnlAddSchoolYear = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSchoolYear = new javax.swing.JTextField();
        btnAddSYCancel = new javax.swing.JButton();
        btnConfirmSY = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 94, 128));
        jPanel2.setForeground(new java.awt.Color(0, 94, 128));
        jPanel2.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        btnDashboard.setText("Dashboard");
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
        });

        btnManagement.setText("Management");
        btnManagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManagementMouseClicked(evt);
            }
        });
        btnManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagementActionPerformed(evt);
            }
        });

        btnSubjSched.setText("Subject Schedule");
        btnSubjSched.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubjSchedMouseClicked(evt);
            }
        });
        btnSubjSched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubjSchedActionPerformed(evt);
            }
        });

        btnStudentGrades.setText("Student’s Grades");
        btnStudentGrades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStudentGradesMouseClicked(evt);
            }
        });

        btnSchoolYear.setText("School Year");
        btnSchoolYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSchoolYearMouseClicked(evt);
            }
        });

        btnCollege.setText("College");
        btnCollege.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCollegeMouseClicked(evt);
            }
        });
        btnCollege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCollegeActionPerformed(evt);
            }
        });

        btnSemester.setText("Semester");
        btnSemester.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSemesterMouseClicked(evt);
            }
        });

        btnCourse.setText("Course");
        btnCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCourseMouseClicked(evt);
            }
        });

        btnEmployee.setText("Employee");
        btnEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmployeeMouseClicked(evt);
            }
        });
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });

        btnSubject.setText("Subject");
        btnSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubjectMouseClicked(evt);
            }
        });

        btnStudent.setText("Student");
        btnStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStudentMouseClicked(evt);
            }
        });
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNavLayout = new javax.swing.GroupLayout(panelNav);
        panelNav.setLayout(panelNavLayout);
        panelNavLayout.setHorizontalGroup(
            panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavLayout.createSequentialGroup()
                .addComponent(btnStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(btnStudentGrades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCollege, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubjSched, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(btnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSemester, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSchoolYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelNavLayout.setVerticalGroup(
            panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnSubjSched)
                .addComponent(btnStudentGrades)
                .addComponent(btnSchoolYear)
                .addComponent(btnCollege, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnSemester)
                .addComponent(btnCourse)
                .addComponent(btnEmployee)
                .addComponent(btnSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnStudent))
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        tblDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrlDashboard.setViewportView(tblDashboard);

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrlDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrlDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(pnlDashboard, "pnlDashboard");

        pnlManagement.setName("pnlManagement"); // NOI18N

        tblManagement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblManagement);

        btnDelete.setBackground(new java.awt.Color(217, 83, 79));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(217, 148, 79));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(90, 153, 207));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlManagementLayout = new javax.swing.GroupLayout(pnlManagement);
        pnlManagement.setLayout(pnlManagementLayout);
        pnlManagementLayout.setHorizontalGroup(
            pnlManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlManagementLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
        );
        pnlManagementLayout.setVerticalGroup(
            pnlManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManagementLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        mainPanel.add(pnlManagement, "pnlManagement");

        pnlAddSubjSched.setName("pnlSubjSched"); // NOI18N

        jLabel1.setText("School Year");

        jLabel2.setText("Semester");

        jLabel3.setText("College Code");

        jLabel4.setText("Day");

        jLabel5.setText("Subject");

        jLabel6.setText("Block No.");

        jLabel8.setText("Employee Name");

        jLabel9.setText("Sequence No.");

        jLabel10.setText("Type");

        txtRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomActionPerformed(evt);
            }
        });

        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });

        jLabel11.setText("Room");

        jLabel12.setText("Time");

        cmbSubjectCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSubjectCodeActionPerformed(evt);
            }
        });

        cmbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        cmbDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDayActionPerformed(evt);
            }
        });

        cmbEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmployeeNameActionPerformed(evt);
            }
        });

        cmbSYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSYearActionPerformed(evt);
            }
        });

        cmbSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSemesterActionPerformed(evt);
            }
        });

        cmbCollegeCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCollegeCodeActionPerformed(evt);
            }
        });

        btnConfirmSched.setBackground(new java.awt.Color(90, 153, 207));
        btnConfirmSched.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmSched.setText("Confirm");
        btnConfirmSched.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmSchedMouseClicked(evt);
            }
        });
        btnConfirmSched.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmSchedActionPerformed(evt);
            }
        });

        btnAddCancel.setBackground(new java.awt.Color(90, 153, 207));
        btnAddCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnAddCancel.setText("Back");
        btnAddCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlAddSubjSchedLayout = new javax.swing.GroupLayout(pnlAddSubjSched);
        pnlAddSubjSched.setLayout(pnlAddSubjSchedLayout);
        pnlAddSubjSchedLayout.setHorizontalGroup(
            pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddSubjSchedLayout.createSequentialGroup()
                .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAddSubjSchedLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmSched, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddSubjSchedLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(pnlAddSubjSchedLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbCollegeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlAddSubjSchedLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(btnAddCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(263, 263, 263))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddSubjSchedLayout.createSequentialGroup()
                                    .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbSYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbSemester, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnlAddSubjSchedLayout.createSequentialGroup()
                                    .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlAddSubjSchedLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlAddSubjSchedLayout.createSequentialGroup()
                                .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlAddSubjSchedLayout.createSequentialGroup()
                                        .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddSubjSchedLayout.createSequentialGroup()
                                        .addGap(0, 2, Short.MAX_VALUE)
                                        .addComponent(jLabel9)))
                                .addGap(18, 18, 18)
                                .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtType, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                    .addComponent(txtSequence, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                    .addComponent(txtRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                    .addComponent(txtTime)))
                            .addGroup(pnlAddSubjSchedLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtBlockNo, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(85, 85, 85))
        );

        pnlAddSubjSchedLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtBlockNo, txtRoom, txtSequence, txtType});

        pnlAddSubjSchedLayout.setVerticalGroup(
            pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddSubjSchedLayout.createSequentialGroup()
                .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddSubjSchedLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbCollegeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBlockNo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(cmbSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbDay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlAddSubjSchedLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAddSubjSchedLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(30, 30, 30)
                                .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(29, 29, 29)
                                .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmbEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtSequence, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))))
                            .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbSYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel12)
                                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 18, Short.MAX_VALUE)
                .addGroup(pnlAddSubjSchedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmSched, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlAddSubjSchedLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtBlockNo, txtRoom, txtSequence, txtType});

        mainPanel.add(pnlAddSubjSched, "pnlAddSubjSched");

        jLabel7.setText("Add School Year");

        txtSchoolYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSchoolYearActionPerformed(evt);
            }
        });

        btnAddSYCancel.setBackground(new java.awt.Color(90, 153, 207));
        btnAddSYCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSYCancel.setText("Back");
        btnAddSYCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSYCancelActionPerformed(evt);
            }
        });

        btnConfirmSY.setBackground(new java.awt.Color(90, 153, 207));
        btnConfirmSY.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmSY.setText("Confirm");
        btnConfirmSY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmSYMouseClicked(evt);
            }
        });
        btnConfirmSY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmSYActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddSchoolYearLayout = new javax.swing.GroupLayout(pnlAddSchoolYear);
        pnlAddSchoolYear.setLayout(pnlAddSchoolYearLayout);
        pnlAddSchoolYearLayout.setHorizontalGroup(
            pnlAddSchoolYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddSchoolYearLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(pnlAddSchoolYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddSchoolYearLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addGap(31, 31, 31)
                        .addComponent(txtSchoolYear, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                        .addGap(416, 416, 416))
                    .addGroup(pnlAddSchoolYearLayout.createSequentialGroup()
                        .addComponent(btnAddSYCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmSY, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))))
        );
        pnlAddSchoolYearLayout.setVerticalGroup(
            pnlAddSchoolYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddSchoolYearLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(pnlAddSchoolYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSchoolYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addGroup(pnlAddSchoolYearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddSchoolYearLayout.createSequentialGroup()
                        .addComponent(btnAddSYCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddSchoolYearLayout.createSequentialGroup()
                        .addComponent(btnConfirmSY, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );

        mainPanel.add(pnlAddSchoolYear, "pnlAddSchoolYears");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubjSchedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubjSchedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubjSchedActionPerformed

    private void btnCollegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCollegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCollegeActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        populatedTable = tblDashboard;
        cacheResultSet(db.fetchStudents());
    }//GEN-LAST:event_formWindowActivated

    private void btnStudentGradesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentGradesMouseClicked
        // TODO add your handling code here:
        cacheResultSet(db.fetchGrades());
        currentData = "StudentGrades";
    }//GEN-LAST:event_btnStudentGradesMouseClicked

    private void btnSubjSchedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjSchedMouseClicked
        // TODO add your handling code here:
        cacheResultSet(db.fetchSubjectSchedules());
        currentData = "SubjectSchedule";
    }//GEN-LAST:event_btnSubjSchedMouseClicked

    private void btnSchoolYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSchoolYearMouseClicked
        // TODO add your handling code here:
        cacheResultSet(db.fetchSchoolYears());
        currentData = "SchoolYear";
    }//GEN-LAST:event_btnSchoolYearMouseClicked

    private void btnCollegeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCollegeMouseClicked
        // TODO add your handling code here:
        cacheResultSet(db.fetchColleges());
        currentData = "College";
    }//GEN-LAST:event_btnCollegeMouseClicked

    private void btnSemesterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSemesterMouseClicked
        // TODO add your handling code here:
        cacheResultSet(db.fetchSemesters());
        currentData = "Semester";
    }//GEN-LAST:event_btnSemesterMouseClicked

    private void btnCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCourseMouseClicked
        // TODO add your handling code here:
        cacheResultSet(db.fetchCourses());
        currentData = "Course";
    }//GEN-LAST:event_btnCourseMouseClicked

    private void btnStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentMouseClicked
        // TODO add your handling code here:
        cacheResultSet(db.fetchStudents());
        currentData = "Students";
    }//GEN-LAST:event_btnStudentMouseClicked

    private void btnEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeMouseClicked
        // TODO add your handling code here:
        cacheResultSet(db.fetchEmployees());
        currentData = "Students";
    }//GEN-LAST:event_btnEmployeeMouseClicked

    private void btnSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubjectMouseClicked
        // TODO add your handling code here:
        cacheResultSet(db.fetchSubjects());
        currentData = "Subject";
    }//GEN-LAST:event_btnSubjectMouseClicked

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
        // TODO add your handling code here:
        switchToCard("pnlDashboard");
        populatedTable = tblDashboard;
        cacheResultSet(db.fetchStudents());
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnManagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagementMouseClicked
        // TODO add your handling code here:
        switchToCard("pnlManagement");
        populatedTable = tblManagement;
        cacheResultSet(db.fetchStudents());
    }//GEN-LAST:event_btnManagementMouseClicked

    private void cmbDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDayActionPerformed

    private void cmbEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEmployeeNameActionPerformed

    private void cmbSYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSYearActionPerformed

    private void cmbSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSemesterActionPerformed

    private void cmbCollegeCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCollegeCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCollegeCodeActionPerformed

    private void btnConfirmSchedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmSchedMouseClicked
        // TODO add your handling code here:
        String selectedDay = (String) cmbDay.getSelectedItem();
        String dayCode;

        dayCode = switch (selectedDay) {
            case "Monday" ->
                "M";
            case "Tuesday" ->
                "T";
            case "Wednesday" ->
                "W";
            case "Thursday" ->
                "Th";
            case "Friday" ->
                "F";
            case "Saturday" ->
                "S";
            case "Sunday" ->
                "Su";
            default ->
                "";
        };
        if (boolAdd) {
            db.addSubjectSchedule(
                    cmbSYear.getSelectedItem().toString().trim(),
                    cmbSemester.getSelectedItem().toString().trim(),
                    "(SELECT college_code FROM finalsoop.college WHERE description = '" + cmbCollegeCode.getSelectedItem().toString().trim() + "')",
                    txtBlockNo.getText().trim(),
                    "(SELECT subject_code FROM finalsoop.subject WHERE description = '" + cmbSubjectCode.getSelectedItem().toString().trim() + "')",
                    dayCode,
                    txtTime.getText(),
                    txtRoom.getText(),
                    txtType.getText(),
                    Integer.parseInt(txtSequence.getText()),
                    "(SELECT employee_id FROM finalsoop.employee WHERE CONCAT(lastname, ', ', firstname) = '" + cmbEmployeeName.getSelectedItem().toString().trim() + "')"
            );
        } else {
            db.updateSubjectSchedule(
                    cmbSYear.getSelectedItem().toString().trim(),
                    cmbSemester.getSelectedItem().toString().trim(),
                    "(SELECT college_code FROM finalsoop.college WHERE description = '" + cmbCollegeCode.getSelectedItem().toString().trim() + "')",
                    txtBlockNo.getText().trim(),
                    "(SELECT subject_code FROM finalsoop.subject WHERE description = '" + cmbSubjectCode.getSelectedItem().toString().trim() + "')",
                    dayCode,
                    txtTime.getText(),
                    txtRoom.getText(),
                    txtType.getText(),
                    Integer.parseInt(txtSequence.getText()),
                    "(SELECT employee_id FROM finalsoop.employee WHERE CONCAT(lastname, ', ', firstname) = '" + cmbEmployeeName.getSelectedItem().toString().trim() + "')"
            );
        }
        switchToCard("pnlManagement");
        db.populateTable(db.fetchSubjectSchedules(), populatedTable);
    }//GEN-LAST:event_btnConfirmSchedMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        boolAdd = true;
        if (currentData.equals("SubjectSchedule")) {
            switchToCard("pnlAddSubjSched");
            populateSchedOptions();
        }
        if (currentData.equals("SchoolYear")) {
            switchToCard("pnlAddSchoolYears");
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void cmbSubjectCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSubjectCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSubjectCodeActionPerformed

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
        boolAdd = false;
        if (currentData.equals("SubjectSchedule")) {
            int row = tblManagement.getSelectedRow();
            populateSchedOptions();
            if (row != -1) {
                String dayCode = switch (tblManagement.getModel().getValueAt(row, 6).toString()) {
                    case "M" ->
                        "Monday";
                    case "T" ->
                        "Tuesday";
                    case "W" ->
                        "Wednesday";
                    case "Th" ->
                        "Thursday";
                    case "F" ->
                        "Friday";
                    case "S" ->
                        "Saturday";
                    case "Su" ->
                        "Sunday";
                    default ->
                        "";
                };
                String collegeCode = findItemInResultSet(db.fetchColleges(), tblManagement.getModel().getValueAt(row, 2).toString(), "college_code", "description");
                switchToCard("pnlAddSubjSched");
                cmbSYear.setSelectedItem(tblManagement.getModel().getValueAt(row, 0).toString());
                cmbSemester.setSelectedItem(tblManagement.getModel().getValueAt(row, 1).toString());
                cmbCollegeCode.setSelectedItem(collegeCode);
                cmbEmployeeName.setSelectedItem(tblManagement.getModel().getValueAt(row, 12).toString());
                cmbSubjectCode.setSelectedItem(tblManagement.getModel().getValueAt(row, 5).toString());
                cmbDay.setSelectedItem(dayCode);
                txtTime.setText(tblManagement.getModel().getValueAt(row, 7).toString());
                txtRoom.setText(tblManagement.getModel().getValueAt(row, 8).toString());
                txtType.setText(tblManagement.getModel().getValueAt(row, 9).toString());
                txtSequence.setText(tblManagement.getModel().getValueAt(row, 10).toString());
                txtBlockNo.setText(tblManagement.getModel().getValueAt(row, 3).toString());
            } else {
                JOptionPane.showMessageDialog(null, "No record selected");
            }
        }
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        int row = tblManagement.getSelectedRow();

        if (currentData.equals("SubjectSchedule")) {
            if (row != -1) {
                String strSubjectCode = tblManagement.getModel().getValueAt(row, 4).toString();
                String strCollegeCode = tblManagement.getModel().getValueAt(row, 2).toString();
                String strSYear = tblManagement.getModel().getValueAt(row, 0).toString();
                String strSemester = tblManagement.getModel().getValueAt(row, 1).toString();
                String strBlockNo = tblManagement.getModel().getValueAt(row, 3).toString();
                String strSequenceNo = tblManagement.getModel().getValueAt(row, 10).toString();
                db.deleteSubjectSchedule(strSubjectCode, strCollegeCode, strSequenceNo, strBlockNo, strSemester, strSYear);
                db.populateTable(db.fetchSubjectSchedules(), populatedTable);
            } else {
                JOptionPane.showMessageDialog(null, "No record selected");
            }
        } else if (currentData.equals("SchoolYear")) {
            if (row != -1) {
                String strSchoolYear = tblManagement.getModel().getValueAt(row, 0).toString();
                db.deleteSchoolYear(strSchoolYear);
                db.populateTable(db.fetchSchoolYears(), populatedTable);
            } else {
                JOptionPane.showMessageDialog(null, "No record selected");
            }
        }
  
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnConfirmSYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmSYMouseClicked
        // TODO add your handling code here:
        if (boolAdd) {
            db.addSchoolYear(
            txtSchoolYear.getText());
        }
        switchToCard("pnlManagement");
            db.populateTable(db.fetchSchoolYears(), populatedTable);
            txtSchoolYear.setText("");

    }//GEN-LAST:event_btnConfirmSYMouseClicked

    private void btnManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManagementActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    private void btnConfirmSYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmSYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmSYActionPerformed

    private void txtRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomActionPerformed

    private void btnConfirmSchedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmSchedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmSchedActionPerformed

    private void btnAddSYCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSYCancelActionPerformed
        // TODO add your handling code here:

        int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog (null, "Cancel Adding of School Year?","WARNING", dialogButton);
            if(dialogButton == JOptionPane.YES_OPTION) {
                switchToCard("pnlManagement");
            if(dialogButton == JOptionPane.NO_OPTION) {
                  remove(dialogButton);
                }
              }
    }//GEN-LAST:event_btnAddSYCancelActionPerformed

    private void btnAddCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCancelMouseClicked
        // TODO add your handling code here:
             int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog (null, "Cancel Adding of Subject Schedule?","WARNING", dialogButton);
            if(dialogButton == JOptionPane.YES_OPTION) {
                switchToCard("pnlManagement");
            if(dialogButton == JOptionPane.NO_OPTION) {
                  remove(dialogButton);
                }
              }
    }//GEN-LAST:event_btnAddCancelMouseClicked

    private void txtSchoolYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSchoolYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSchoolYearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new schoolManagementMainUI().setVisible(true);
        }
    });
}

    private void switchToCard(String cardName) {
    CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
    cardLayout.show(mainPanel, cardName);
}

    private void cacheResultSet(java.sql.ResultSet rs) {
    if (rs == null) {
        System.out.println("ResultSet is null");
    }
    if (populatedTable == null) {
        System.out.println("populatedTable is null");
    }
    currentRs = rs;
    db.populateTable(currentRs, populatedTable);
}

    private void populateSchedOptions() {
    try {
        ResultSet rs = null;
        rs = db.fetchSchoolYears();
        while (rs.next()) {
            cmbSYear.addItem(rs.getString("syear"));
        }
        rs = db.fetchSemesters();
        while (rs.next()) {
            cmbSemester.addItem(rs.getString("semester"));
        }
        rs = db.fetchColleges();
        while (rs.next()) {
            cmbCollegeCode.addItem(rs.getString("description"));
        }
        rs = db.fetchEmployees();
        while (rs.next()) {
            cmbEmployeeName.addItem(rs.getString("lastname") + ", " + rs.getString("firstname"));
        }
        rs = db.fetchSubjects();
        while (rs.next()) {
            cmbSubjectCode.addItem(rs.getString("description"));
        }
    } catch (Exception e) {
        System.out.println(e);
    }
}

    public String findItemInResultSet(ResultSet rs, String targetValue, String columnName, String targetColumn) {
    try {
        while (rs.next()) {
            String value = rs.getString(columnName);
            if (value.equals(targetValue)) {
                value = rs.getString(targetColumn);
                return value;
            }
        }
    } catch (Exception e) {
        System.out.println(e);
    }
    return null;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddCancel;
    private javax.swing.JButton btnAddSYCancel;
    private javax.swing.JButton btnCollege;
    private javax.swing.JButton btnConfirmSY;
    private javax.swing.JButton btnConfirmSched;
    private javax.swing.JButton btnCourse;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnManagement;
    private javax.swing.JButton btnSchoolYear;
    private javax.swing.JButton btnSemester;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton btnStudentGrades;
    private javax.swing.JButton btnSubjSched;
    private javax.swing.JButton btnSubject;
    private javax.swing.JComboBox<String> cmbCollegeCode;
    private javax.swing.JComboBox<String> cmbDay;
    private javax.swing.JComboBox<String> cmbEmployeeName;
    private javax.swing.JComboBox<String> cmbSYear;
    private javax.swing.JComboBox<String> cmbSemester;
    private javax.swing.JComboBox<String> cmbSubjectCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelNav;
    private javax.swing.JPanel pnlAddSchoolYear;
    private javax.swing.JPanel pnlAddSubjSched;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlManagement;
    private javax.swing.JScrollPane scrlDashboard;
    private javax.swing.JTable tblDashboard;
    private javax.swing.JTable tblManagement;
    private javax.swing.JTextField txtBlockNo;
    private javax.swing.JTextField txtRoom;
    private javax.swing.JTextField txtSchoolYear;
    private javax.swing.JTextField txtSequence;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
